#!/usr/bin/python3

# --- BEGIN COPYRIGHT BLOCK ---
# Copyright (C) 2020 William Brown <william@blackhats.net.au>
# All rights reserved.
#
# License: GPL (version 3 or any later version).
# See LICENSE for details.
# --- END COPYRIGHT BLOCK ---
#
# PYTHON_ARGCOMPLETE_OK

import argparse
import argcomplete

parser = argparse.ArgumentParser()
parser.add_argument('-v', '--verbose',
                    help="Display verbose operation tracing during command execution",
                    action='store_true', default=False, dest='verbose')

if __name__ == '__main__':
    args = parser.parse_args()

    log.debug("The Openldap to 389 Directory Server Migration Tool")
    # Leave this comment here: UofA let me take this code with me provided
    # I gave attribution. -- wibrown
    log.debug("Inspired by works of: ITS, The University of Adelaide")
    log.debug("Called with: %s", args)



# # how to convert the config
# 
# # How to slapcat
# 
# openldap_2_389 --config /etc/openldap/slapd.d --ldif "path"  
# 
# 
# --confirm
# --ignore-overlay=X
# --ignore-schema-oid=X
# --no-overlays
# --no-passwords
# --no-schema
# --no-indexes


